// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file proto/story.proto (package ventura.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/story.proto.
 */
export const file_proto_story: GenFile = /*@__PURE__*/
  fileDesc("ChFwcm90by9zdG9yeS5wcm90bxIKdmVudHVyYS52MSJSChpHZXROZXh0U3RvcnlTZWdtZW50UmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhAKCHN0b3J5X2lkGAIgASgJEhEKCWNob2ljZV9pZBgDIAEoCSJwChtHZXROZXh0U3RvcnlTZWdtZW50UmVzcG9uc2USEwoLc2VnbWVudF91cmwYASABKAkSDwoHdHRzX3VybBgCIAEoCRIrCgticmFuY2hfbWV0YRgDIAEoCzIWLnZlbnR1cmEudjEuQnJhbmNoTWV0YSIoCgpCcmFuY2hNZXRhEhoKEm5leHRfY2hvaWNlX3Byb21wdBgBIAEoCTJ2CgxTdG9yeVNlcnZpY2USZgoTR2V0TmV4dFN0b3J5U2VnbWVudBImLnZlbnR1cmEudjEuR2V0TmV4dFN0b3J5U2VnbWVudFJlcXVlc3QaJy52ZW50dXJhLnYxLkdldE5leHRTdG9yeVNlZ21lbnRSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message ventura.v1.GetNextStorySegmentRequest
 */
export type GetNextStorySegmentRequest = Message<"ventura.v1.GetNextStorySegmentRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string story_id = 2;
   */
  storyId: string;

  /**
   * @generated from field: string choice_id = 3;
   */
  choiceId: string;
};

/**
 * Describes the message ventura.v1.GetNextStorySegmentRequest.
 * Use `create(GetNextStorySegmentRequestSchema)` to create a new message.
 */
export const GetNextStorySegmentRequestSchema: GenMessage<GetNextStorySegmentRequest> = /*@__PURE__*/
  messageDesc(file_proto_story, 0);

/**
 * @generated from message ventura.v1.GetNextStorySegmentResponse
 */
export type GetNextStorySegmentResponse = Message<"ventura.v1.GetNextStorySegmentResponse"> & {
  /**
   * URL for the video segment
   *
   * @generated from field: string segment_url = 1;
   */
  segmentUrl: string;

  /**
   * URL for the text-to-speech audio
   *
   * @generated from field: string tts_url = 2;
   */
  ttsUrl: string;

  /**
   * @generated from field: ventura.v1.BranchMeta branch_meta = 3;
   */
  branchMeta?: BranchMeta;
};

/**
 * Describes the message ventura.v1.GetNextStorySegmentResponse.
 * Use `create(GetNextStorySegmentResponseSchema)` to create a new message.
 */
export const GetNextStorySegmentResponseSchema: GenMessage<GetNextStorySegmentResponse> = /*@__PURE__*/
  messageDesc(file_proto_story, 1);

/**
 * @generated from message ventura.v1.BranchMeta
 */
export type BranchMeta = Message<"ventura.v1.BranchMeta"> & {
  /**
   * Placeholder for metadata about the new branch
   *
   * @generated from field: string next_choice_prompt = 1;
   */
  nextChoicePrompt: string;
};

/**
 * Describes the message ventura.v1.BranchMeta.
 * Use `create(BranchMetaSchema)` to create a new message.
 */
export const BranchMetaSchema: GenMessage<BranchMeta> = /*@__PURE__*/
  messageDesc(file_proto_story, 2);

/**
 * The main service for interacting with stories.
 *
 * @generated from service ventura.v1.StoryService
 */
export const StoryService: GenService<{
  /**
   * Retrieves the next segment of a story based on user choice.
   *
   * @generated from rpc ventura.v1.StoryService.GetNextStorySegment
   */
  getNextStorySegment: {
    methodKind: "unary";
    input: typeof GetNextStorySegmentRequestSchema;
    output: typeof GetNextStorySegmentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_story, 0);

